"""Aggiunto user_id con nomi constraint

Revision ID: 6285039c579b
Revises: d9fe76187919
Create Date: 2025-05-22 19:27:31.427474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6285039c579b'
down_revision = 'd9fe76187919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key('fk_inventoryitem_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('inventory_meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key('fk_inventorymeta_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('inventory_meta', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventorymeta_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventoryitem_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
